import '../models/course_model.dart';

final List<Course> dummyCourses = [
  Course(
    id: '',
    title: 'Flutter App Development',
    description: 'Learn to build beautiful mobile apps with Flutter and Dart.',
    duration: 40,
    instructor: 'John Doe',
    imageUrl: 'https://miro.medium.com/v2/resize:fit:1400/0*LpYMQ2UKZOvUB-JO',
    category: 'Mobile Development',
    tags: ['flutter', 'dart', 'mobile'],
    level: 'Beginner',
    rating: 4.8,
    studentsEnrolled: 1200,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Full-Stack Web Development',
    description: 'Become a full-stack developer using React, Node.js, and MongoDB.',
    duration: 60,
    instructor: 'Sarah Johnson',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYzJnfk53aqLKxZIfTVAxt5PGLKcjMtuKX-Q&s',
    category: 'Web Development',
    tags: ['fullstack', 'react', 'node', 'mongodb'],
    level: 'Intermediate',
    rating: 4.6,
    studentsEnrolled: 900,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Python for Data Science',
    description: 'Master data analysis and machine learning using Python.',
    duration: 50,
    instructor: 'Mike Ross',
    imageUrl: 'https://media.geeksforgeeks.org/wp-content/cdn-uploads/20230318230239/Python-Data-Science-Tutorial.jpg',
    category: 'Data Science',
    tags: ['python', 'data-science', 'machine-learning'],
    level: 'Beginner',
    rating: 4.9,
    studentsEnrolled: 1500,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Advanced Java Programming',
    description: 'Deep dive into Java design patterns, concurrency, and backend development.',
    duration: 45,
    instructor: 'Rachel Zane',
    imageUrl: 'https://media.geeksforgeeks.org/wp-content/uploads/20230823152056/What-is-Advance-JAVA.png',
    category: 'Programming',
    tags: ['java', 'backend', 'design-patterns'],
    level: 'Advanced',
    rating: 4.7,
    studentsEnrolled: 700,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the essentials of good user interface and user experience design.',
    duration: 30,
    instructor: 'Emily Clark',
    imageUrl: 'https://careercollegeindia.com/blog/wp-content/uploads/2024/09/UI-UX-Designer-scaled.jpg',
    category: 'Design',
    tags: ['ui', 'ux', 'figma'],
    level: 'Beginner',
    rating: 4.5,
    studentsEnrolled: 1100,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'AWS Cloud Practitioner Certification',
    description: 'Prepare for AWS certification and master cloud concepts.',
    duration: 35,
    instructor: 'Tom Hardy',
    imageUrl: 'https://d2908q01vomqb2.cloudfront.net/9109c85a45b703f87f1413a405549a2cea9ab556/2020/11/10/AWSCloudPractitionerEssentialsBlog_300x150.png',
    category: 'Cloud Computing',
    tags: ['aws', 'cloud', 'certification'],
    level: 'Intermediate',
    rating: 4.8,
    studentsEnrolled: 600,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Cybersecurity Basics',
    description: 'Understand network security, encryption, and protection against cyber threats.',
    duration: 25,
    instructor: 'Oliver Queen',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPGz8iL2UI5xMAJRtLtX35Rg5XxLv0CGN4ZA&s',
    category: 'Cybersecurity',
    tags: ['security', 'network', 'hacking'],
    level: 'Beginner',
    rating: 4.4,
    studentsEnrolled: 800,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Machine Learning with TensorFlow',
    description: 'Train machine learning models using TensorFlow and deep learning techniques.',
    duration: 55,
    instructor: 'Sophia Lee',
    imageUrl: 'https://blog.paperspace.com/content/images/size/w1050/2021/01/0_szgpfwmBY_CuZwP8-2.png',
    category: 'Artificial Intelligence',
    tags: ['machine-learning', 'tensorflow', 'deep-learning'],
    level: 'Advanced',
    rating: 4.9,
    studentsEnrolled: 950,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Photography for Beginners',
    description: 'Capture amazing photos and learn the fundamentals of digital photography.',
    duration: 20,
    instructor: 'Emma Watson',
    imageUrl: 'https://media.restless.co.uk/uploads/2020/06/a_beginners_guide_to_photography_hero.jpg',
    category: 'Photography',
    tags: ['photography', 'dslr', 'editing'],
    level: 'Beginner',
    rating: 4.5,
    studentsEnrolled: 500,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Digital Marketing Essentials',
    description: 'Master SEO, content marketing, and social media strategies.',
    duration: 30,
    instructor: 'Chris Martin',
    imageUrl: 'https://online.hbs.edu/Style%20Library/api/resize.aspx?imgpath=/PublishingImages/blog/posts/digital-marketing-skills.jpg&w=1200&h=630',
    category: 'Marketing',
    tags: ['seo', 'content', 'social-media'],
    level: 'Intermediate',
    rating: 4.7,
    studentsEnrolled: 850,
    language: 'English',
  ),
    Course(
    id: '',
    title: 'Blockchain Development with Solidity',
    description: 'Learn to build decentralized apps (dApps) using Ethereum and Solidity.',
    duration: 45,
    instructor: 'Bruce Wayne',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1pD9La8fPDxNmhOXkMUVEmlsV1jYfCPNYxA&s',
    category: 'Blockchain',
    tags: ['blockchain', 'solidity', 'ethereum'],
    level: 'Advanced',
    rating: 4.8,
    studentsEnrolled: 550,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'iOS App Development with Swift',
    description: 'Build beautiful iOS apps using Swift and SwiftUI.',
    duration: 50,
    instructor: 'Tony Stark',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3b_pnUy8EsOuT6opXqM7RGoEEbOKnxAtlmQ&s',
    category: 'Mobile Development',
    tags: ['ios', 'swift', 'swiftui'],
    level: 'Intermediate',
    rating: 4.7,
    studentsEnrolled: 600,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Game Development with Unity',
    description: 'Create 2D and 3D games using Unity and C#.',
    duration: 55,
    instructor: 'Clark Kent',
    imageUrl: 'https://cdn.prod.website-files.com/5b651f8b5fc94c4e27470a81/622227fd2ce3cc0455a88166_blog-gamedev-fullsize.png',
    category: 'Game Development',
    tags: ['game', 'unity', 'csharp'],
    level: 'Intermediate',
    rating: 4.6,
    studentsEnrolled: 750,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Ethical Hacking and Penetration Testing',
    description: 'Learn to ethically hack systems and protect against attacks.',
    duration: 40,
    instructor: 'Natasha Romanoff',
    imageUrl: 'https://www.xenonstack.com/hubfs/ethical-hacking-vs-penetration-testing.png',
    category: 'Cybersecurity',
    tags: ['hacking', 'pentesting', 'security'],
    level: 'Advanced',
    rating: 4.8,
    studentsEnrolled: 670,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Introduction to Artificial Intelligence',
    description: 'Discover the basics of AI, including search algorithms and neural networks.',
    duration: 35,
    instructor: 'Peter Parker',
    imageUrl: 'https://be10x.in/wp-content/uploads/2024/01/Introduction-to-Artificial-Intelligence.jpg',
    category: 'Artificial Intelligence',
    tags: ['ai', 'neural-networks', 'search'],
    level: 'Beginner',
    rating: 4.5,
    studentsEnrolled: 890,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'WordPress for Beginners',
    description: 'Create and manage your own website using WordPress.',
    duration: 25,
    instructor: 'Diana Prince',
    imageUrl: 'https://www.elegantthemes.com/blog/wp-content/uploads/2023/07/WordPress-for-Beginners.jpg',
    category: 'Web Development',
    tags: ['wordpress', 'cms', 'website'],
    level: 'Beginner',
    rating: 4.3,
    studentsEnrolled: 450,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Cloud Computing with Microsoft Azure',
    description: 'Learn cloud fundamentals and deploy applications using Azure.',
    duration: 40,
    instructor: 'Steve Rogers',
    imageUrl: 'https://dotnettrickscloud.blob.core.windows.net/article/120220728114146.webp',
    category: 'Cloud Computing',
    tags: ['azure', 'cloud', 'devops'],
    level: 'Intermediate',
    rating: 4.7,
    studentsEnrolled: 500,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'React Native for Mobile Apps',
    description: 'Build cross-platform mobile apps with React Native.',
    duration: 45,
    instructor: 'Barry Allen',
    imageUrl: 'https://miro.medium.com/v2/resize:fit:1400/1*9HczlTj75TQJLbnIGek7Lw.png',
    category: 'Mobile Development',
    tags: ['react-native', 'mobile', 'javascript'],
    level: 'Intermediate',
    rating: 4.5,
    studentsEnrolled: 770,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Data Structures and Algorithms in Python',
    description: 'Master DSA concepts for coding interviews and development.',
    duration: 50,
    instructor: 'Bruce Banner',
    imageUrl: 'https://media.geeksforgeeks.org/wp-content/uploads/20211118125839/PythonDataStructuresandAlgorithms.png',
    category: 'Programming',
    tags: ['dsa', 'python', 'algorithms'],
    level: 'Intermediate',
    rating: 4.8,
    studentsEnrolled: 1020,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Advanced Photoshop Techniques',
    description: 'Take your photo editing skills to the next level with Photoshop.',
    duration: 30,
    instructor: 'Wanda Maximoff',
    imageUrl: 'https://i.ytimg.com/vi/_nQKf_Fgk_M/maxresdefault.jpg',
    category: 'Design',
    tags: ['photoshop', 'editing', 'creative'],
    level: 'Advanced',
    rating: 4.6,
    studentsEnrolled: 380,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Deep Learning with PyTorch',
    description: 'Learn to build deep neural networks with PyTorch framework.',
    duration: 50,
    instructor: 'Stephen Strange',
    imageUrl: 'https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/misc-pytorch-course-launch-cover-white-text-black-background.jpg',
    category: 'Artificial Intelligence',
    tags: ['deep-learning', 'pytorch', 'neural-networks'],
    level: 'Advanced',
    rating: 4.8,
    studentsEnrolled: 600,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Kubernetes for Beginners',
    description: 'Master container orchestration using Kubernetes.',
    duration: 35,
    instructor: 'Nick Fury',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTRlJXYIJn_nnvzFVV8w_iZ4BM1SwVcX51KQ&s',
    category: 'Cloud Computing',
    tags: ['kubernetes', 'containers', 'devops'],
    level: 'Intermediate',
    rating: 4.7,
    studentsEnrolled: 560,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Financial Markets and Investing',
    description: 'Understand how financial markets work and how to invest wisely.',
    duration: 30,
    instructor: 'Pepper Potts',
    imageUrl: 'https://media.geeksforgeeks.org/wp-content/cdn-uploads/20220916181534/Financial-Markets.png',
    category: 'Finance',
    tags: ['investing', 'stock-market', 'finance'],
    level: 'Beginner',
    rating: 4.4,
    studentsEnrolled: 620,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Big Data Analytics with Hadoop',
    description: 'Process and analyze large datasets with Hadoop and MapReduce.',
    duration: 55,
    instructor: 'Scott Lang',
    imageUrl: 'https://media.geeksforgeeks.org/wp-content/uploads/20200620130644/traditional-way-to-solve-bigdata.png',
    category: 'Data Science',
    tags: ['big-data', 'hadoop', 'analytics'],
    level: 'Advanced',
    rating: 4.6,
    studentsEnrolled: 470,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Augmented Reality with ARKit',
    description: 'Develop AR applications for iOS devices using ARKit.',
    duration: 40,
    instructor: 'Gamora',
    imageUrl: 'https://martech.org/wp-content/uploads/2018/06/ARkit2_Lifestyle-room_06042018-1.jpg',
    category: 'Augmented Reality',
    tags: ['ar', 'arkit', 'ios'],
    level: 'Intermediate',
    rating: 4.7,
    studentsEnrolled: 300,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Business Communication Skills',
    description: 'Enhance your communication skills for corporate success.',
    duration: 20,
    instructor: 'Happy Hogan',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2iK0UkYKTR5kRBMezuhFCDVKu5tmNSaS4Og&s',
    category: 'Business',
    tags: ['communication', 'presentation', 'business'],
    level: 'Beginner',
    rating: 4.5,
    studentsEnrolled: 550,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Docker for Developers',
    description: 'Package your applications using Docker and learn containerization.',
    duration: 30,
    instructor: 'Peter Quill',
    imageUrl: 'https://www.docker.com/app/uploads/2024/09/2400x1260_docker-for-web-developers-1110x583.png',
    category: 'Cloud Computing',
    tags: ['docker', 'containers', 'devops'],
    level: 'Intermediate',
    rating: 4.7,
    studentsEnrolled: 690,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Entrepreneurship 101',
    description: 'Learn how to launch and grow your startup from scratch.',
    duration: 30,
    instructor: 'Shuri',
    imageUrl: 'https://miro.medium.com/v2/resize:fit:1400/1*1KvyZjqg3dhuUHu4eBlGhQ.png',
    category: 'Business',
    tags: ['startup', 'entrepreneur', 'business'],
    level: 'Beginner',
    rating: 4.6,
    studentsEnrolled: 420,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Video Editing with Premiere Pro',
    description: 'Master video editing techniques using Adobe Premiere Pro.',
    duration: 35,
    instructor: 'Vision',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ762-xGtQBVhbb5rVaVOuyyjbUpJkV8s-_HA&s',
    category: 'Design',
    tags: ['video-editing', 'premiere', 'creative'],
    level: 'Intermediate',
    rating: 4.7,
    studentsEnrolled: 370,
    language: 'English',
  ),
  Course(
    id: '',
    title: 'Introduction to Quantum Computing',
    description: 'Learn the basics of quantum algorithms and qubits.',
    duration: 50,
    instructor: 'Reed Richards',
    imageUrl: 'https://www.investopedia.com/thmb/mL2a2GAnrskc-ebuq-UT-GM_bwU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/quantum-computing.asp-FINAL-1-68635090f7534414b9173598fe0ad95c.png',
    category: 'Quantum Computing',
    tags: ['quantum', 'algorithms', 'physics'],
    level: 'Advanced',
    rating: 4.8,
    studentsEnrolled: 240,
    language: 'English',
  ),
];
